### ISSUE TITLE
RxJavaFx Project Name

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxJavaFX#2]
Is the name of this project correct? Anything better?

What should the artifact and module names be?

**Comment by cbeams** [comment]
> Is the name of this project correct? Anything better?

Yes, I'd say it's as clear and concise as possible.

> What should the artifact and module names be?

`io.reactivex:rxjava-fx:x.y.z` looks reasonable to me. The dash in `rxjava-fx` is used for consistency with the other RxJava\* projects. `rxjava-javafx` might be more correct, but I imagine users won't have any trouble understanding the former, less redundant form.

**Comment by thomasnield** [comment]
Closing this issue as the RxJavaFX name seemed to fit consensus. It has been released to Maven Central under this name.
