### ISSUE TITLE
testPeriodicScheduling() test failing Travis build

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxJavaFX#22]
Merging #20 seems to have caused a build issue caused by `testPeriodicScheduling()` failing

**Comment by thomasnield** [comment]
How odd. I added some JavaDocs just to make a non-impacting change. It built successfully this time. Looking at the Travis build history, it looks like this test method succeeds or fails in an indeterministic manner.

**Comment by thomasnield** [comment]
This seems be indeterministic, which is slightly unsettling. However, I have only seen this happen on Travis and nowhere else. Perhaps the reliance on explicit timing in the test is what is causing the issue. I can't investigate this for awhile but if somebody wants to take a look I will not be opposed.

**Comment by hastebrot** [comment]
Hmm, delicious, looks like a Heisenbug.  I had some interesting problems with weak references in observables. But it would require more inspection to isolate the real cause.

~~**Edit:** Aww dammit, more like a Schrödinbug.~~

**Comment by thomasnield** [comment]
Yeah Netflix folks didn't know much about JavaFX so they were eager to pass ownership of this project. I've kept things together but never figure out the problem with the Scheduler test.

**Comment by hastebrot** [comment]
I'd first need to reproduce the bug. Reactive extensions are very interesting.

**Comment by thomasnield** [comment]
Yeah I rely heavily on RxJava hence why I stopped using ReactFX and became involved with this. My suggestion would be to looks at the weird timing mechanism. I think its timed for a second before it automatically fails.

**Comment by hastebrot** [comment]
The method we speak about for reference: https://github.com/ReactiveX/RxJavaFX/blob/aed2dee32c/src/test/java/rx/schedulers/JavaFxSchedulerTest.java#L72-L101

**Comment by thomasnield** [comment]
Confirmed. That is correct.

**Comment by thomasnield** [comment]
Hopefully this issue has been resolved with the new trampoline mechanism in the `JavaFxScheduler`, thanks to @akarnokd's help. If the builds are consistently successful and hangups no longer happen, I will close this issue.

**Comment by thomasnield** [comment]
Darn, I did get another failure. Again this only happens with Travis. 
https://travis-ci.org/ReactiveX/RxJavaFX/builds/115742006

**Comment by akarnokd** [comment]
Travis is hectic with timed tests; you may think 50ms or 200ms is precisely executed, but not always. Perhaps if you double all times involved, the test succeeds (more often).

**Comment by thomasnield** [comment]
I'm not well-versed in Travis but I was beginning to suspect that, especially considering the explicit timing involved in the test. Thanks and I'll implement that now!

**Comment by thomasnield** [comment]
Alright, I'll monitor future builds and see if it behaves now.

**Comment by thomasnield** [comment]
This seems to be testing consistently after implementing @akarnokd's advice.
