### ISSUE TITLE
doOnXXXCount() Operators

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxJavaFX#31]
I added some [`doOnXXXCount()` operators to RxKotlinFX](https://github.com/thomasnield/RxKotlinFX#operators). Specifically these are the `doOnNextCount()`, `doOnErrorCount()`, and `doOnCompletedCount()` operators, which are analogous to `doOnNext()`, `doOnCompleted()`, etc already found in RxJava. The only difference is these emit the cumulative emission counts for each of those events. This is helpful to post updates on a UI showing how many items have been "processed" by an `Observable`. 

Here is the example written in Kotlin: 

``` kotlin
val source = Observable.range(1,1000)
val processedCountLabel = Label()

source.map { it * 10 }
     .doOnNextFx { processedCountLabel.text = "Processed $it items" }
     .subsribe { doSomethingWith(it) }
```

I added these to RxKotlinFX because extension functions make this more elegant and less cumbersome to use. However, I could port this to ~~RxJava~~ RxJavaFX and allow the `Operator` to be passed to the `lift()` method.

Does anybody feel this would be helpful to add/not add?

**Comment by akarnokd** [comment]
These look like very special use operators and I'm not convinced they should be in RxJava. You can have custom `Operator`s in some tool-lib outside RxJava.

**Comment by thomasnield** [comment]
Even for RxJavaFX? Did you mix up your project notifications by any chance : )P

I think there could be utility for RxJavaFX, since it is common for user interfaces to show a status label reading "Processed [x number] of items." This is a common side effect need in the context of UI's, although it could be argued it could be put in @davidmoten's RxJava-Extras or another library, which may allow this project to be more focused.

However, these doOnXXXCount() actions would conveniently need to execute on the FX thread... which may warrant putting them in this project...

**Comment by thomasnield** [comment]
I'll let others comment on this proposal over the next week before I take any action. Do we want to start adding JavaFX-specific Operators?

**Comment by akarnokd** [comment]
> However, I could port this to RxJava and allow the Operator to be passed to the lift() method.

Maybe I didn't express myself precisely, I'm not convinced `Observable.doOnNextCount` should exist. It is up to you if FX has room and the means for it.

**Comment by thomasnield** [comment]
Oh, my bad sorry : ) That is not the first time I've done that. I'll make that edit.

**Comment by thomasnield** [comment]
I think I'm deciding against this simply because Java does not have extension functions like Kotlin and this would be somewhat cumbersome to use without them. I'd prefer to keep this library lightweight and somewhat elegant, but if anybody feels differently let me know by the end of the week.
