### ISSUE TITLE
Planning for RxJava 2.0

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxJavaFX#41]
I read the documentation on the release candidate of RxJava 2.0, and it is pretty clear disruptive  (but good) changes are on the horizon that directly affect RxJavaFX. 

https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0

I haven't dived deep into this yet or even messed with the released candidate,  but it does seem a major refactoring is necessary since RxJava was basically rewritten from scratch with the coming 2.0 release.

I'll investigate this further, but it seems RxJavaFX would want to use the Flowable rather than the Observable. I am not a backpressure expert,  but my understanding is backpressure cannot be helped with UI events since a person cannot be directed to slow down emissions. Therefore, a Flowable makes sense, and I can't think of any factories in RxJavaFX that shouldn't use it. 

I think the best approach is to release RxJavaFX 1.0 and 2.0 as separate maintained versions, aligned  with the respective RxJava counterparts. The same will likely happen with RxKotlinFX.

Again,  I didn't dig deep in RxJava 2.0 but I think I have a high level of understanding.  If anybody has any concerns, ideas,  feedback,  or just anything they would want to see in RxJavaFX 1.0 and 2.0, please let us know here on this issue.

**Comment by thomasnield** [comment]
Sorry, long day.  I read this backwards. Flowable supports bakpressure. Observable does not. This therefore will require little change thankfully.

**Comment by thomasnield** [comment]
Still keeping this open since 1.0 and 2.0 versions will still need to be managed

**Comment by thomasnield** [comment]
2.x branch has been created. Some refactoring has been done although still a lot of work left to resolve compile errors.

**Comment by thomasnield** [comment]
RxJava2 has been released so this probably needs to become priority at some point. Unfortunately right now I'm busy with several projects, and while I hate creating contingencies I can't personally prioritize this until [RxJava-JDBC](https://github.com/davidmoten/rxjava-jdbc) and [RxJava-Extras](https://github.com/davidmoten/rxjava-extras) gets ported to RxJava2. I will get to this likely once that happens, but if anybody wants to contribute porting this to RxJava2 I will not hesitate to accept help.

**Comment by thomasnield** [comment]
For handling lack of nullable types in RxJava2, I may have to follow suit with what ReactFX does and have non-nullable versions of factories. The nullable factories will have to use an Optional packaged with the library.

**Comment by ghost** [comment]
Any hints how to convert the JavaFxScheduler class to 2.0? I tried to convert it myself but failed. It did not execute anything. I'm pretty new to JavaRx in general and would really appreciate any help. Also I currently only need this class to execute things on the main thread. As far as I can see this is the only blocker to use RxJava in combination with RxJavaFX without using the JavaFX specific bindings?

**Comment by akarnokd** [comment]
``` java
io.reactivex.Scheduler swingWorker = 
    io.reactivex.schedulers.Schedulers.from(SwingUtilities::invokeLater);
```

**Comment by thomasnield** [comment]
@akarnokd you must mean `Schedulers.from(Platform::runLater)`

**Comment by akarnokd** [comment]
I don't know JavaFX just wanted to show an example with Swing as a quick workaround. You may still want to implement a proper Scheduler as there is no need for the trampolining `from` does.

**Comment by thomasnield** [comment]
Good point. I may migrate this to RxJava 2.0 sooner than planned (maybe this weekend) as an exercise as well as to get it out of the way.

**Comment by thomasnield** [comment]
Started working on this. I'm going to simultaneously release RxJavaFX 1.0 alongside RxJavaFX 2.0. If anybody has any last minute requests for features they'd like to see, let me know. I'm also going to remove the `CompositeObservable` @Beta annotation.

**Comment by thomasnield** [comment]
I think for RxJavaFX 2.0, I am going to have the factories `valuesOf()` and `nullableValuesOf()`, which will behave opposite to RxJavaFX 1.0's `valuesOf()` and `nonNullValuesOf()`. 

The `valuesOf()` in 2.0 will not emit null values and simply ignore them. `nullableValuesOf()` will yield an `Observable<Optional<T>>`. I imagine we want to avoid working with Optionals as much as possible, and in most cases we will not want nulls anyway. 

I believe this will be the smoothest transition so folks do not suddenly find `valuesOf()` emitting Optionals when they refactor to 2.0. I'll leave RxJavaFX 1.0 alone with the current factories as I see no good reason to have them mirror 2.0's factories. I do not want to cause severe breaking changes where folks may be depending on `valuesOf()` to emit nulls anyway.

**Comment by thomasnield** [comment]
RxJavaFX 2.0 is now done. I'm going to do a sweep one more time and then do a pre-release.
