### ISSUE TITLE
Question: Possibility to redirect change lister notifications to happen on another thread?

### ISSUE THREAD

**Issue by Tosken1337** [ReactiveX/RxJavaFX#46]
Hi,

i have a quit complex application which has a ObservableList<Pages> inside the data model.
Many ui controls and other parts of the business logic are bound to the list to update when changes are made.
Until now all changes of the list are triggered inside the JavaFX application thread. Which was good because otherwise i get an exception that it is the wrong thread when a bound control of the ui wants to reflect the changes.

Is it possible to use RXJavaFX to wrap the list and create another binding which notifies all these observer on the JavaFx Thread. It is important not to change the code parts where the original ObserableList is modified.

I thought about something like that:
1. Create an rx obserable from the change events of the original list.
2. Use oberserveOn to notify observers on the specific thread.
3. Create an javafx oberserable list from this rx obersable which will be used to bind the ui controls.

I have problems with point 3. how is it possible to create an javafx obersablelist from this obserable?

Thanks and best regards

**Comment by thomasnield** [comment]
Have you read this chapter in the guide yet? Might help you with the third item if I understand correctly.

https://thomasnield.gitbooks.io/rxjavafx-guide/content/4.%20Collections.html

**Comment by Tosken1337** [comment]
Yes i have read the whole book. Thats not exactly what i want. I know how to turn the ObersableList ind an rx obserable of list chnage events or in a stream of added items. But is it possible te transform it back to an plain ObserbableList which is bound or backed by an rx obserable ?

**Comment by thomasnield** [comment]
Using RxJava to bind an `ObservableList<T>` to an `ObservableList<R>` with a variety of transformation between the two is something that I have thought about for a long time. The most effective way I have found to do this is to make one `ObservableList` the receiver of items from an `Observable` built off another `ObservableList`. 

You can do this atomically by providing an entire `List` that is set to the receiving `ObservableList`. 

```java
ObservableList<String> strings = FXCollections.observableArrayList();
ObservableList<Integer> distinctLengths = FXCollections.observableArrayList();

JavaFxObservable.changesOf(strings)
      .flatMap(list ->
              Observable.from(list)
                  .map(String::length)
                  .distinct()
                  .toList()
      ).subscribe(distinctLengths::setAll);
```

This atomic approach distinctly turns each request into a batch of items. If you use `switchMap()`, you can easily kill previous processing for previous changes, so you can chase after the latest one. Of course, you will need to parallelize so the current thread pushing the current request can kill previous requests running on other threads. 

```java
ObservableList<String> strings = FXCollections.observableArrayList();
ObservableList<Integer> distinctLengths = FXCollections.observableArrayList();

JavaFxObservable.changesOf(strings)
        .switchMap(list ->
                Observable.from(list)
                    .map(String::length)
                    .distinct()
                    .toList()
                    .subscribeOn(Schedulers.computation())
        ).observeOn(JavaFxScheduler.getInstance())
         .subscribe(distinctLengths::setAll);
```

If you do not want to collect into an intermediary list, you can use `doOnSubscribe()` to clear the target `ObservableList` at the start of each request, and then `add()` each item to the target `ObservableList`. 

```java
ObservableList<String> strings = FXCollections.observableArrayList();
ObservableList<Integer> distinctLengths = FXCollections.observableArrayList();

JavaFxObservable.fromObservableList(strings)
        .switchMap(list ->
                Observable.from(list)
                    .doOnSubscribe(() -> Platform.runLater(distinctLengths::clear))
                    .map(String::length)
                    .distinct()
        ).observeOn(JavaFxScheduler.getInstance())
        .subscribe(distinctLengths::add);   
```

In Kotlin, you can use the `apply()` function to encapsulate this behavior, syntactically speaking. I do this quite a bit. Just remember to save the `Subscription` if you ever need to dispose it.

```kotlin
val strings = FXCollections.observableArrayList<String>()

val distinctLengths = FXCollections.observableArrayList<Int>().apply {
    strings.onChangedObservable()
            .switchMap{ list ->
                Observable.from<String>(list)
                        .doOnSubscribeFx { clear() }
                        .map { it.length }
                        .distinct()
            }.observeOnFx()
            .subscribe { add(it) }
    }
```


Here is a working example:

```java
import javafx.application.Platform;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.embed.swing.JFXPanel;
import rx.Observable;
import rx.observables.JavaFxObservable;

public class Test {

    public static void main(String[] args) {
        new JFXPanel(); //initialize JavaFX

        Platform.runLater(() -> {
            ObservableList<String> strings = FXCollections.observableArrayList("Alpha","Beta");
            ObservableList<Integer> distinctLengths = FXCollections.observableArrayList();

            JavaFxObservable.changesOf(strings)
                    .witchMap(list ->
                            Observable.from(list)
                                    .map(String::length)
                                    .distinct()
                                    .toList()
                                    .subscribeOn(Schedulers.computation())
                    ).observeOn(JavaFxScheduler.getInstance())
                    .subscribe(distinctLengths::setAll);


            //print the contents of `distinctLengths` every time it changes
            JavaFxObservable.changesOf(distinctLengths)
                    .subscribe(System.out::println);

            strings.add("Gamma");
            strings.remove("Beta");
            strings.add("Epsilon");
        });
    }
}
```

**OUTPUT:**

```
[5, 4]
[5, 4]
[5]
[5, 7]
```
