### ISSUE TITLE
Invalidation factory for javafx.beans.Observable

### ISSUE THREAD

**Issue by protogenes** [ReactiveX/RxJavaFX#47]
Add a factory for invalidations of any FX observable.
I think propagating the FX observable instead of some constant is of better value.

```java
public static Observable<javafx.beans.Observable> invalidationsOf(final javafx.beans.Observable fxObservable) {
    return ObservableSource.fromInvalidations(fxObservable);
}
```

```java
public class ObservableSource {
	private ObservableSource() {}

	public static Observable<javafx.beans.Observable> fromInvalidations(javafx.beans.Observable fxObservable) {
		return Observable.create((ObservableEmitter<javafx.beans.Observable> emitter) -> {
			final InvalidationListener listener = emitter::onNext;
			fxObservable.addListener(listener);
			emitter.setDisposable(JavaFxSubscriptions.unsubscribeInEventDispatchThread(() -> fxObservable.removeListener(listener)));
		});
	}
}
```

**Comment by thomasnield** [comment]
Makes perfect sense. I'll implement this later in 1.0 as well as the 2.0 branch.

**Comment by thomasnield** [comment]
Wouldn't it make more sense to emit an `ObservableValue<T>` rather than just a JavaFX `Observable`? The JavaFX `Observable` (not Rx one) does not have the `getValue()` method, but the `ObservableValue<T>` does. I imagine that would be more useful. 

```java
    public static <T> Observable<ObservableValue<T>> fromInvalidations(final ObservableValue<T> fxObservable) {
        return Observable.create(subscriber -> {
            final InvalidationListener listener = s -> subscriber.onNext(fxObservable);
            fxObservable.addListener(listener);
            subscriber.add(JavaFxSubscriptions.unsubscribeInEventDispatchThread(() -> fxObservable.removeListener(listener)));
        });
    }
```

Would it also make sense to overload a `Property<T>` version as well? That way we can have access to a `setValue()` method for each emitted `Property<T>`?

```java
    public static <T> Observable<Property<T>> fromInvalidations(final Property<T> fxProperty) {
        return Observable.create(subscriber -> {
            final InvalidationListener listener = s -> subscriber.onNext(fxProperty);
            fxProperty.addListener(listener);
            subscriber.add(JavaFxSubscriptions.unsubscribeInEventDispatchThread(() -> fxProperty.removeListener(listener)));
        });
    }
```

**Comment by protogenes** [comment]
The main difference is, that `ObservableList<>`, `ObservableSet<>`, `ObservableMap<>` and `Property<>` all implement the `Observable` interface and this could be used without knowing the specific type. If you know it you should use `valuesOf`, `changesOf` and so on.

**Comment by thomasnield** [comment]
@protogenes that makes sense. Okay I'll implement your way.

**Comment by thomasnield** [comment]
@protogenes Implemented in 1.x. I'll do 2.x as soon as I merge the new Scheduler for that branch. Let me know if that's ready.
