### ISSUE TITLE
JavaFxScheduler broken on (at least) 8u112

### ISSUE THREAD

**Issue by protogenes** [ReactiveX/RxJavaFX#48]
Currently the JavaFxScheduler depends on the keyframe finish callback of JavaFX animations.
But animations with a duration of zero will never start, thus the callback (of the keyframe) will not be called.
See javafx.animation.Animation.java (JDK 8u112):
```java
boolean impl_startable(boolean forceSync) {
    return (fromDuration(getCycleDuration()) > 0L)
        || (!forceSync && clipEnvelope.wasSynched());
}
```

One possible solution is to use the finish callback of the timeline instead: `timer.setOnFinished(executeOnce);`

**Comment by thomasnield** [comment]
That's not good,  okay this makes sense I'll see if I can implement in th  next few days. Feel free to put in a PR if you want to beat me to it.

**Comment by protogenes** [comment]
I thought about introducing a short path
```java
if (delayTime == 0)
	return schedule(action);
```
but I find it very hard to fully understand the implications or changes in behaviour in that complex implementation.
From what I understand by looking at the tests is the following:
- nested actions should be executed after the invoking action has finished in contrast to a direct recursive call on the EDT
- the trampoline implementation has a fast path for the top call and some logic to unwind the nested calls https://github.com/ReactiveX/RxJavaFX/blob/2.x/src/main/java/rx/schedulers/JavaFxScheduler.java#L190
- there seems to be no guarantee that the queue is populated in a way which has the nested actions at the head, because earlier or concurrent invocations of `schedule` can be mixed in https://github.com/ReactiveX/RxJavaFX/blob/2.x/src/main/java/rx/schedulers/JavaFxScheduler.java#L171
- thus the implementations does not guarantee that nested actions run directly after their invoking action without interference of independent actions
Is this a defect or is the implementation trying to achieve behaviour that is not neccessary and is therefor overly complex?

I'm currently rewriting the whole thing to work according to my understanding, any thoughts on the matter will be very appreciated.

**Comment by thomasnield** [comment]
Read this issue we had a year ago. We need that complex setup because I found complex usage cases need it. 

https://github.com/ReactiveX/RxJavaFX/issues/27

Also do you have a use case example hat shows a broken behavior?

**Comment by protogenes** [comment]
I'm not sure which behaviour to expect from the scheduler. Look at my extended test case https://gist.github.com/protogenes/a5bd7b08fea64aa89cd3f3f5bef81f24
which modifies the original (braces used for nested actions) test{ third{ second{ first } } to test{ A{ B{ C, D } } , E }
The test schedules A and E, A schedules B, and B schedules C and D. Which order is to be expected: ABCDE or AEBCD? Because of the unwind logic I expected it to be ABCDE, but it isn't.

Regarding #27 the `wip` counter is there to prevent recursive calls and to unroll recursive actions.
Starvation of the JavaFX Thread with recursion is a problem if indefinite recursive calls are created (thus wip not reaching zero).
Starvation in general is avoided because every action will be executed by a separate `Platform.runLater`, but I'm not sure how and if the platform event handling itself will protect from starvation if we push a sufficient large amount of actions for processing.

**Comment by thomasnield** [comment]
@protogenes this is an interesting discussion, and @akarnokd feel free to add anything if you like. With the test case you presented above, I want to highlight the behavior is still deterministic. It will go through the current tasks and then do a second pass at the tasks scheduled by those previous tasks. This makes the scheduler highly resilient to complex scheduling cases. 

It does add some overhead yes, and @akarnokd acknowledged that in #27  but deemed it necessary.  Complicated scheduling operations against a single thread that also schedules against itself can be hard to get right, and I have found this implementation works much better than "leaner" implementations that backfired (this is [what it looked like before the trampoline overhaul](https://github.com/ReactiveX/RxJavaFX/blob/00ffe2b6eb7b14daca9eeec6d5d9b3a7952c6064/src/main/java/rx/schedulers/JavaFxScheduler.java)). 

Regarding this statement....

>Starvation in general is avoided because every action will be executed by a separate Platform.runLater, but I'm not sure how and if the platform event handling itself will protect from starvation if we push a sufficient large amount of actions for processing.

I can see where you are coming from and that might be true. However, the EDT/JavaFX thread is sensitive to a high volume of tasks anyway, and can become laggy when it has a large backlog of work.  So my thought is this is a situation you want to avoid in the first place! To avoid starvation, you should keep that queued work off the FX thread and on worker threads, and leverage backpressure as well as throttling/buffering/switching operators to keep the FX thread from receiving too many tasks at once.

**Comment by thomasnield** [comment]
You likely read this already, but here is the [chapter from the eBook covering Switching, Throttling, and Buffering](https://thomasnield.gitbooks.io/rxjavafx-guide/content/9.%20Switching,%20Throttling,%20and%20Buffering.html). You will want to use those strategies (as well as backpressure) to keep the FX thread from receiving too many tasks.

**Comment by protogenes** [comment]
I have read your book earlier this year as an introduce to Rx, it is a good read, but I just recently started using RxJava(FX) in a large project fending off ReactFX and all its problems and unexpected behaviour.

I'm interested in the actual problems you had in #27, because the only direct change is that a top level `schedule` within the JavaFX thread is called directly in contrast to being delayed with `Platform.runLater`.
I claim there is no guarantee that its recursive actions won't be delayed, if another asynchronous source uses the same worker:
```
async schedule          --A--------
schedule in FX Thread   B......----
processing on FX Thread  B...A.-C.-
recursive schedule         C
#pending Platform.run     1111110
wip                    001122110110
Queue head             ---AAACCC---
                          -CC---
                           --
```
As you can see the recursive action C will be delayed because A is in the queue in front of it and will be executed during the second pass/unroll instead. If your original problems arose from delayed actions which were directly `schedule`d on the FX Thread, they seem only fixed by chance.

Furthermore I want to raise the question why the queue won't be drained completely on each execution.
Firstly it would solve above issue and secondly reduce the load on `Platform.runLater` which is advised in its documentation.
This would simplify the code and I claim it will not introduce new chances of starvation of the FX thread. The FX thread would starve if an unlimited amount of actions would be appended in any of the two possible cases of the current implementation:
- recursive actions would increment the `wip` counter and lead to an infinite second pass, which may not be helped with Switching, Throttling or Buffering (I can't imagine how to create an observable cycle for this to happen, tho)
- actions scheduled from other threads would also repost the `Worker` with `Platform.runLater` and cause additional overhead and load on the FX thread.

For my understanding I still would like to know which execution order is desired. BCA vs. BAC in the current example or ABCDE vs. AEBCD from the previous test, respectively.
If we want to favor recursive tasks as in ABCDE we could keep the logic based on `wip`, but I would not feel like maintaining that implementation.

I hope I could put my thoughts across.

P.S. thanks for the link, I was in desperate search of switching earlier today.

**Comment by thomasnield** [comment]
Man, i need a nitro coffee or two before I go through your analysis, and it's too late at night for that. I'll take a look at this tomorrow, Hopefully @akarnokd can spare a moment to chime in on this as well. I definitely appreciate your thoroughness and thought put into this. We will make sure this is indeed the optimal implementation.

**Comment by akarnokd** [comment]
I don't know about JavaFX. If there is no (reliable) delayed scheduling option, such as with a plain `Executor`, we use helper schedulers (Single in 2.x and GenericScheduledExecutorService in 1.x) to do the delayed schedule and within that we reschedule the actual task on the original scheduler.

**Comment by protogenes** [comment]
I think I understand the original issue as follows
```java
Property<String> fxProperty = ...
JavaFxObservable.valuesOf(fxProperty).subscribeOn(JavaFxScheduler.platform()).subscribe(System.out::println);
fxProperty.setValue("Hello World!");
```
I added the explicit `subscribeOn` for clarity, but `JavaFxObservable` does this already.
One would expect to see `Hello World!` to be printed, if the code was executed on the Java FX thread, but it won't because the old naive implementation would delay the subscription with `Platform.runLater` and the change will be lost. If run from another thread, the `setValue` must have been called within the FX thread and is allowed to be lost anyway because of the inherent asynchronous situation.
The problem arises as we expect the `JavaFxScheduler` to behave like the immediate/direct scheduler for `valuesOf` called in the FX thread.
@akarnokd I think `Platform.runLater` is reliable and the problem is deterministic and applies not only to Java FX.
I see two possible solutions:
- make the `JavaFxScheduler` process all actions directly when `schedule`d from the FX thread or
- decide if to use the immediate or the FX scheduler when subscribing with `valueOf`, ...

Solution 1 is what the current implementation tries but does not guarantee, as I have shown earlier.
Solution 2 seems easy in the simple example, but I deem it difficult for more complex scenarios when subscription happens later.

@thomasnield you realise that only the FX Properties with a connection to the UI need to live on the FX thread? Therfor your approach will do just fine in most of the cases, but I think providing overloads which allow to specify a custom `Scheduler` would help.

Anyway I have pushed two simplified implementations of the JavaFxScheduler depending on which execution order is desired:
https://github.com/protogenes/RxJavaFX/commit/845ffe333fc9f43905a28d53f89ae9b83d720b58
https://github.com/protogenes/RxJavaFX/commit/ab52bbd81f8d300ad67e7f44df6402151b0d3dd7

**Comment by thomasnield** [comment]
@protogenes I'll play with this in the next few days once I get a chance and do some review. I appreciate the scrutiny here and perhaps what we will do if we go forward with one of the implementations is create a beta version of the Scheduler in the `JavaFxScheduler` class. I do want to push this thing through several test cases and I'm glad you wrote some unit tests.

**Comment by thomasnield** [comment]
@protogenes is this branch ready to merge? Is the new `Scheduler` implementation the same as the one you made for 1.x?
