### ISSUE TITLE
Update README and guide for RxJavaFX 2.0

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxJavaFX#52]
The README and [_Learning RxJava with JavaFX_](https://www.gitbook.com/book/thomasnield/rxjavafx-guide/details) eBook need to be updated to reflect RxJavaFX 2.0's features and API.

**Comment by thomasnield** [comment]
If anybody wants to help with updating these documentations, please feel free to contribute submissions.

**Comment by thomasnield** [comment]
README has been updated. I'll go through it again later to make sure I didn't miss anything.

**Comment by chronodm** [comment]
Is the 2.x branch of the book viewable anywhere? I couldn't see a way to get to it on GitBook.

**Comment by thomasnield** [comment]
@chronodm I'm not sure how to do it from the website. But you can clone it with GIT and read in Atom Editor or something. 

Clone URL: https://git.gitbook.com/thomasnield/rxjavafx-guide.git

I haven't gotten far in switching the eBook over to RxJava 2.0. I've been busy with the [_Learning RxJava_ Packt book](https://www.packtpub.com/application-development/learning-rxjava) which will cover RxJava 2.0 more thoroughly than this guide. If I do get a chance to finish the eBook, I will likely keep it UI-centric and omit Flowables and backpressure, and I will tell folks to read the Packt book for full coverage of RxJava 2.0 (it includes a few RxJavaFX examples too!). 

Because there is not enough change going on, Google announced yesterday Kotlin to be an official supported language for Android. This will put a huge amount of momentum behind Kotlin as a JVM language, and I foresee Kotlin will increasingly be used with JavaFX via TornadoFX. I'm in the middle of discussing a pure RxKotlin implementation, so there is quite a bit happening right now.

**Comment by thomasnield** [comment]
Just a quick update, I'm realistically not going to be updating the _Learning RxJava with JavaFX_ eBook anytime soon to cover RxJava 2.x. There's a lot on my place with O'Reilly, KotlinConf, and campaigning Kotlin as a data science platform. 

I still use the RxJavaFX stack heavily in Kotlin and will be ready to provide feedback. But I wouldn't mind if someone wanted to take over updating the eBook.

**Comment by georgeVasiliu** [comment]
Are there many, major differences between the RxJavaFX for RxJava 1.0 and the RxJavaFx for RxJava 2.x ? I wouldn't mind looking at RxJava 2.x and observe it's new features and update the eBook (I'm especially interested in RxKotlinFX to be honest), as long as I have at least a few key-points on which to look-out for or some facts/features that are game-changers for the library and must be documented to reflect the 2.x version.

**Comment by thomasnield** [comment]
@georgeVasiliu There are some significant differences that would break the code examples between 1.x and 2.x, for both RxJavaFX and RxKotlinFX. 

Either way, I got the 2.x version of the book done today. Feel free to take a look for yourselves guys!

https://www.gitbook.com/book/thomasnield/rxjavafx-guide/details
