### ISSUE TITLE
JavaFxObservable.actionEventsOf is only listening on the first click of the button

### ISSUE THREAD

**Issue by xRicochet** [ReactiveX/RxJavaFX#66]
Hi. I'm trying to create an Observable out of a button click but apparently it's running only on the first click. The other clicks does nothing. Any ideas why this would happen?

        Button loadUsersButton = new Button("Load users");
        BorderPane root = new BorderPane();
        root.setTop(loadUsersButton);
        HBox githubInfo = new HBox();
        List<VBox> listOfUserInfo = Arrays.asList(new VBox(), new VBox(), new VBox());
        githubInfo.getChildren().addAll(listOfUserInfo);
        root.setCenter(githubInfo);
        final Subject<ActionEvent> loadButtonSubject = PublishSubject.create();

        JavaFxObservable.actionEventsOf(loadUsersButton).subscribe(loadButtonSubject);

        loadButtonSubject
                .map(ae -> githubExternalService.getUsers())
                .flatMapIterable(x -> x)
                .take(3)
                .map(this::createText)
                .map(text -> {
                    VBox vBox = new VBox();
                    vBox.getChildren().add(text);
                    return vBox;
                }).subscribe(
                vbox -> githubInfo.getChildren().add(vbox),
                System.err::println);
        return root;

**Comment by thomasnield** [comment]
Your pattern seems valid. Without running this, the only thing that stands out is is the `take()` operator. You sure you are not cutting the stream off prematurely? 

Can you try to create a minimal, self-contained example that I can run?

**Comment by thomasnield** [comment]
By the way, you are adding the same vbox on every action. I'm pretty sure this is the problem. I'll close unless you can provide further evidence of something being wrong.
