### ISSUE TITLE
JavaFX 11 Planning

### ISSUE THREAD

**Issue by thomasnield** [ReactiveX/RxJavaFX#70]
I've not kept up with Java 9/10 releases and chose to align RxJavaFX with TorndoFX's approach of waiting for Java 11. 

@protogenes has already started filing issues and PR's, and I know other libraries [have already transitioned as well](https://twitter.com/eryzhikov/status/1038810882585886720). 

I'm going to try my best to get RxJavaFX moved to Java 11 in the next few weeks.

**Comment by thomasnield** [comment]
For reference:
http://docs.gluonhq.com/javafx11/#introduction

**Comment by thomasnield** [comment]
Proposed version number convention for Java 11 build will be `2.11.x`. 

For Java 8, it will shift to `2.8.x`. 

I'd prefer to keep the major version number pegged to RxJava.

**Comment by thomasnield** [comment]
I created a new 2.11.x branch and migrated to Java 11 successfully. Migration took only a few minutes and all unit tests have passed. UI opened up fine too.

**Comment by thomasnield** [comment]
Migration to Java 11 is successful. This version can be seen on 2.11.x branch. I'm going to review other issues and see if I can get other requests implemented before release.

**Comment by brainbytes42** [comment]
Hi,

two short remarks on versioning, as I was just evaluating the current state and dependencies of RxJava and RxJavaFX for a new and some existing projects:

It seems, RxJavaFx 2.11.x is on track with RxJava 3.x as of this commit (https://github.com/ReactiveX/RxJavaFX/commit/74aa7e0f7633abb01070c4e820dc4097faf535bd), but the major version wasn't updated as planned in the comment above (https://github.com/ReactiveX/RxJavaFX/issues/70#issuecomment-420409071)?
> I'd prefer to keep the major version number pegged to RxJava.
Maybe it would be good to fix this, as I was a little sad at first, not to be able to use RxJava3 with this really nice JavaFx-Interoperability.

Second remark: I'm (still) stuck with Java 8 for some projects, as of company requirements... Even there, I could use RxJava3, but not with RxJavaFX 2.8.x, as this hasn't been raised to RxJava 3.x as far as I can see. I don't know how high the effort would be to have a RxJavaFX 3.8.x version? From the commit above, it seems manageable...? ;-) At least, it would match RxJava's target-compatibility, which is Java 8 for v3...
