### ISSUE TITLE
Java 11 Automatic-Module-Name

### ISSUE THREAD

**Issue by claudio-rosati** [ReactiveX/RxJavaFX#74]
RxJava added `Automatic-Module-Name: io.reactivex.rxjava2` to the manifest, in order to have a small step into the Java 11 full module transition. This was in the following clause of the `build.graddle` file:

```
jar {
    manifest {
        name = "rxjava"
        instruction "Bundle-Vendor", "RxJava Contributors"
        instruction "Bundle-DocURL", "https://github.com/ReactiveX/RxJava"
        instruction "Import-Package", "!org.junit,!junit.framework,!org.mockito.*,!org.testng.*,*"
        instruction "Eclipse-ExtensibleAPI", "true"
        instruction "Automatic-Module-Name", "io.reactivex.rxjava2"
    }
}
```

Can this be made also for RxJavaFX?

**Comment by thomasnield** [comment]
I'll take a look. First I need to get the current codebase deployed for Java 11 which I have been having challenges with.

**Comment by claudio-rosati** [comment]
Thank you
