### ISSUE TITLE
2.11.0-RC16 / error: cannot access JavaFxObserver

### ISSUE THREAD

**Issue by brainbytes42** [ReactiveX/RxJavaFX#78]
Hi,

gradle just pulled the newes version, and failed... previously, I was using 2.2.2, which worked fine.

now with 2.11.0-RC16, it crashed with following message:

> error: cannot access JavaFxObserver
> import io.reactivex.rxjavafx.observers.JavaFxObserver;
>                                       ^
>   bad class file: [...]\.gradle\caches\modules-2\files-2.1\io.reactivex.rxjava2\rxjavafx\2.11.0-RC16\66e34cc6d518010a46cd9816c5dca70d3a40e1e3\rxjavafx-2.11.0-RC16.jar(io/reactivex/rxjavafx/observers/JavaFxObserver.class)
>     class file has wrong version 55.0, should be 52.0
>     Please remove or make sure it appears in the correct subdirectory of the classpath.
> :[...]:compileJava FAILED

I had RxJava included with wildcard:
    compile group: 'io.reactivex.rxjava2', name: 'rxjava', version: '2+'

Fixing it to 2.2.2 (last version before, I think) solves the issue.

**Comment by thomasnield** [comment]
Try using RC30? And you you are also using Java 11?

**Comment by thomasnield** [comment]
Sorry, use RC22.

**Comment by brainbytes42** [comment]
there is only RC16 here...?
https://repo.maven.apache.org/maven2/io/reactivex/rxjava2/rxjavafx/

no, I'm using java 8 - is the 2.11... version Java 11 only?

**Comment by thomasnield** [comment]
@brainbytes42 yes, 2.11.x only works with Java 11 with OpenJFX. 

Use earlier versions for Java 8, which will soon be developed under 2.8.x versions.
