### ISSUE TITLE
Error - cannot access io.reactivex.Observable   

### ISSUE THREAD

**Issue by permiakover** [ReactiveX/RxJavaFX#93]
Hello, I'd like to share my experience with RxJavaFx while getting started with Java 8.
According to guidelines I added maven dependency 

```
 <dependency>
        <groupId>io.reactivex.rxjava2</groupId>
        <artifactId>rxjavafx</artifactId>
        <version>2.2.2</version>
    </dependency>
```

and tried to apply an example from the RxJavaFx Guide Book. And from the beggining I got **"cannot access io.reactivex.Observable"** trying to use  

```
JavaFxObservable.actionEventsOf(button)
                .subscribe(System.out::println);  
```
on a new project.  The solution was to add manually  a dependency for   

```
<dependency>
            <groupId>io.reactivex.rxjava2</groupId>
            <artifactId>rxjava</artifactId>
            <version>2.2.19</version>
</dependency>
```

RxJavaFx version 2.2.2 brings the rxjava version 2.2.16 and such problem.

**Comment by m-a-g-i-c** [comment]
I had a similar problem when I used rxJava2 and rxJava3 in the same project. Check that you don't import rxJava3 lib. I'm using gradle and all works, my build.gradle:
`  
plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.9'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.reactivex.rxjava3:rxjava:3.0.13-RC2'
    implementation 'io.reactivex.rxjava2:rxjavafx:2.2.2'
    // https://mvnrepository.com/artifact/io.reactivex.rxjava2/rxjava
    implementation group: 'io.reactivex.rxjava2', name: 'rxjava', version: '2.2.2'

    implementation("com.google.guava:guava:30.1.1-jre")
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

javafx {
    version = "16"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}
`

**Comment by m-a-g-i-c** [comment]
I had a similar problem when I was using rxJava2 and rxJava3 in the same project. Make sure you don't import rxJava3 in your code. I am using gradle and everything works, my build.gradle:
```
plugins {
id 'java'
id 'application'
id 'org.openjfx.javafxplugin' version '0.0.9'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
mavenCentral()
}

dependencies {
implementation 'io.reactivex.rxjava3:rxjava:3.0.13-RC2'
implementation 'io.reactivex.rxjava2:rxjavafx:2.2.2'
// https://mvnrepository.com/artifact/io.reactivex.rxjava2/rxjava
implementation group: 'io.reactivex.rxjava2', name: 'rxjava', version: '2.2.2'

implementation("com.google.guava:guava:30.1.1-jre")
testCompile group: 'junit', name: 'junit', version: '4.12'
}

javafx {
version = "16"
modules = [ 'javafx.controls', 'javafx.fxml' ]
}
```
