### ISSUE TITLE
Is there a plan to use RXJava 3 ?

### ISSUE THREAD

**Issue by torakiki** [ReactiveX/RxJavaFX#96]
Hi, 
not sure this is the right channel. I'm starting a new JavaFX application and I'm evaluating options. I see RXJava2 will be maintained until Feb 2021 so I was wandering what's the plan for RXJavaFX.
Thanks

**Comment by thomasnield** [comment]
HI @torakiki, I've been rather busy with other projects nowadays but I do welcome contributors. I think I need to pass ownership of RxJavaFX to someone else willing to keep it going.

**Comment by torakiki** [comment]
Ok, thanks for the info
